### ISSUE TITLE
Improve handling of failed deployments when using bulk application deployments

### ISSUE THREAD

**Issue by korvoj** [nmaas-platform/nmaas-platform#127]
When an instance encounters an error during a bulk deployment, its state is set to Failed. Clicking on the settings icon and choosing "Application instance details" redirects to a non-existent page, e.g., https://$NMAAS_INSTANCE/instances/undefined. Additionally, the (i) icon next to "Failed" does not show any tooltip and does not respond on a click. It would be useful if the user can be presented with an option to see the reason why the deployment failed (timeout, non-existent application, non-existent application version, non-existent domain...).

![image](https://github.com/nmaas-platform/nmaas-platform/assets/4062681/8b68471c-bd8e-40e5-8d79-62f19ffc32b2)

**Comment by llopat** [comment]
@korvoj 

Right, the tooltip with error message with behave as you describe, this implementation is already in place but due to some bug the message is not displayed.

Correct, in some "Failed" cases the option of accessing application instance details should be hidden (if no instance identifier is available).

In addition, the Domain codename should be displayed also for Failed deployments but this information is not yet provided by backend.

**Comment by llopat** [comment]
@kbeyro 

I think only one improvement remained. When a deployment of an instance failed and the instance identifier is not available, the "Check state" menu option is still present under the cogwheel menu. It seems that in such case the entire cogwheel icon should be hidden.
